
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
  adminer:
    image: butopea/adminer
    restart: always
    ports:
      - "7080:8080"
    environment:
      ADMINER_DB: postits_database
      ADMINER_DRIVER: pgsql
      ADMINER_USERNAME: app
      ADMINER_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      ADMINER_SERVER: database
      ADMINER_AUTOLOGIN: 1
###< doctrine/doctrine-bundle ###
