<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251219220639 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE post_it_tag (post_it_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (post_it_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_CDEF2C3EB8464527 ON post_it_tag (post_it_id)');
        $this->addSql('CREATE INDEX IDX_CDEF2C3EBAD26311 ON post_it_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE post_it_tag ADD CONSTRAINT FK_CDEF2C3EB8464527 FOREIGN KEY (post_it_id) REFERENCES post_it (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_it_tag ADD CONSTRAINT FK_CDEF2C3EBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE post_it_tag DROP CONSTRAINT FK_CDEF2C3EB8464527');
        $this->addSql('ALTER TABLE post_it_tag DROP CONSTRAINT FK_CDEF2C3EBAD26311');
        $this->addSql('DROP TABLE post_it_tag');
        $this->addSql('DROP TABLE tag');
    }
}
